name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python manage.py migrate
        
    # - name: Check for pdb.set_trace()
    #   run: |
    #     set -e
    #     # Use grep to search for pdb.set_trace() in Python files
    #     # Adjust the file pattern as needed
    #     if grep -r -n 'pdb.set_trace()' .; then
    #       echo "Found pdb.set_trace() in the code. Please remove it before committing."
    #       exit 1
    #     else
    #       echo "No instances of pdb.set_trace() found in the code."
    #     fi


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          echo "Win#755855" > id_rsa
          chmod 600 id_rsa
          ssh-keyscan -t rsa 16.16.207.23 >> known_hosts

      - name: Deploy code
        run: |
          git pull
          sudo systemctl restart nginx